name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DB_USER: ${{ vars.DB_USER }}
  DB_PASS: ${{ vars.DB_PASS }}
  DB_NAME: ${{ vars.DB_NAME }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies  
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          echo "DB_USER=$DB_USER" >> .env
          echo "DB_PASS=$DB_PASS" >> .env
          echo "DB_NAME=$DB_NAME" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Start database
        run: npm run actionsdb:up

      - name: Wait for PostgreSQL
        run: |
          timeout 30s bash -c 'until nc -z localhost 5432; do sleep 1; done'
          sleep 5
          
      - name: Run migrations
        run: npm run migrate
        