name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies  
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          echo "DB_USER=myuser" >> .env
          echo "DB_PASS=mypass" >> .env
          echo "DB_NAME=outbuild" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Start database
        run: npm run actionsdb:up
      
      - name: Debug Docker
        run: |
          docker ps
          docker logs $(docker ps -q)
          docker network ls
          netstat -tulpn

      - name: Wait for PostgreSQL
        run: |
          timeout 30s bash -c 'until nc -z localhost 5432; do sleep 1; done'
          sleep 5
          
      - name: Run migrations
        run: npm run migrate
        env:
          DB_USER: myuser
          DB_PASS: mypass
          DB_NAME: outbuild
          DB_HOST: localhost
          DB_PORT: 5432
        